name: yolov9segconda
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - gitpython
  - ipython
  - matplotlib>=3.2.2
  - numpy>=1.18.5
  - opencv>=4.1.1
  - pillow>=7.1.2
  - psutil
  - pyyaml>=5.3.1
  - requests>=2.23.0
  - scipy>=1.4.1
  - tqdm>=4.64.0
  - tensorboard>=2.4.1
  - pandas>=1.1.4
  - seaborn>=0.11.0
  - albumentations>=1.0.3
  - pycocotools>=2.0
  - thop
  - pytorch>=1.7.0
  - torchvision>=0.8.1
  - cudatoolkit=10.1 
  - protobuf<=3.20.1
  - pip:
      - thop

